#services:
#  app:
#    image: hanjihae/catube-app:latest
#    container_name: catube
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_PORT}/${SPRING_APPLICATION_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    networks:
#      - app-network
#
#  batch:
#    image: hanjihae/catube-app:latest
#    container_name: catube-batch
#    build:
#      context: ../catube-batch
#      dockerfile: ./Dockerfile
#    ports:
#      - "8081:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_PORT}/${SPRING_APPLICATION_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    networks:
#      - app-network
#
#  db:
#    image: mysql:8
#    ports:
#      - "${DB_PORT}:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - db-data:/var/lib/mysql
#    networks:
#      - app-network
#
#  web:
#    container_name: web
#    image: hanjihae/second-eyes-web:new
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#    networks:
#      - app-network
#
#  nginx:
#    container_name: nginx
#    image: hanjihae/second-eyes-nginx
#    ports:
#      - 80:80
#    depends_on:
#      - web
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge
#
#volumes:
#  db-data:
